# Generated by Django 3.2.7 on 2021-11-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
